// components/product/ProductCard.vue
<template>
  <NuxtLink :to="`/producto/${product.slug}`" class="group">
    <div class="border border-gray-100 rounded-xl overflow-hidden bg-white hover:shadow-xl hover:shadow-primary-100/50 transition-all duration-300">
      <!-- Image -->
      <div class="aspect-square bg-gradient-to-br from-gray-50 to-primary-50/30 relative overflow-hidden">
        <img
          v-if="product.images?.[0]"
          :src="product.images[0].url"
          :alt="product.name"
          class="w-full h-full object-contain p-4 group-hover:scale-105 transition-transform duration-300"
        />
        <div v-else class="w-full h-full flex items-center justify-center text-gray-300">
          <ImageOff class="w-12 h-12" />
        </div>

        <!-- Wishlist heart -->
        <button
          class="absolute top-3 right-3 z-10 w-8 h-8 rounded-full bg-white/90 shadow-sm flex items-center justify-center transition-colors hover:bg-red-50"
          :class="inWishlist ? 'text-red-500' : 'text-gray-400'"
          @click.prevent="handleWishlist"
        >
          <Heart class="w-4 h-4" :class="inWishlist ? 'fill-current' : ''" />
        </button>

        <!-- Badges -->
        <div class="absolute top-3 left-3 flex flex-col gap-1.5">
          <span
            v-if="product.sale_price && product.sale_price < product.base_price"
            class="bg-red-500 text-white text-xs font-bold px-2.5 py-1 rounded-full shadow-sm"
          >
            -{{ calcDiscount(product.base_price, product.sale_price) }}%
          </span>
          <span
            v-if="product.is_featured"
            class="bg-primary-500 text-white text-xs font-bold px-2.5 py-1 rounded-full shadow-sm"
          >
            NUEVO
          </span>
        </div>

        <!-- Hover add to cart overlay -->
        <div class="absolute inset-x-0 bottom-0 p-3 translate-y-full group-hover:translate-y-0 transition-transform duration-300 z-10">
          <button
            class="w-full flex items-center justify-center gap-2 bg-primary-600 hover:bg-primary-700 text-white text-sm font-semibold py-2.5 rounded-lg transition-colors shadow-lg"
            @click.prevent="handleAddToCart"
          >
            <ShoppingCart class="w-4 h-4" />
            Agregar al carro
          </button>
        </div>
      </div>

      <!-- Info -->
      <div class="p-4">
        <p class="text-xs text-gray-400 mb-1 uppercase tracking-wide">{{ product.brand?.name }}</p>
        <h3 class="text-sm font-medium text-gray-800 line-clamp-2 min-h-[2.5rem] group-hover:text-primary-600 transition-colors">
          {{ product.name }}
        </h3>
        <div class="mt-3">
          <ProductPriceDisplay :product="product" />
        </div>
        <p v-if="product.stock > 0" class="text-xs text-emerald-600 mt-2 flex items-center gap-1">
          <span class="w-1.5 h-1.5 rounded-full bg-emerald-500 inline-block" />
          En stock
        </p>
        <p v-else class="text-xs text-red-500 mt-2 flex items-center gap-1">
          <span class="w-1.5 h-1.5 rounded-full bg-red-400 inline-block" />
          Sin stock
        </p>
      </div>
    </div>
  </NuxtLink>
</template>

<script setup lang="ts">
import { ShoppingCart, ImageOff, Heart } from "lucide-vue-next";
import type { Product } from "~/types";
import { calcDiscount } from "~/utils/format";

const props = defineProps<{ product: Product }>();

const { addToCart } = useCart();
const { show: showToast } = useToast();
const { isInWishlist, toggleWishlist } = useWishlist();
const { isAuthenticated } = useAuth();

const inWishlist = computed(() => isInWishlist(props.product.id));

async function handleAddToCart() {
  const ok = await addToCart(props.product);
  if (ok) {
    showToast("Producto agregado al carrito");
  } else {
    showToast("No se pudo agregar al carrito", "error");
  }
}

function handleWishlist() {
  if (!isAuthenticated.value) {
    navigateTo(`/login?redirect=${encodeURIComponent(useRoute().fullPath)}`);
    return;
  }
  toggleWishlist(props.product.id);
}
</script>

// src/ui/components/plp/product-card.tsx
"use client";

import type React from "react";
import Link from "next/link";
import Image from "next/image";
import { Plus } from "lucide-react";
import { Button } from "@/ui/components/ui/button";
import { Badge } from "@/ui/components/ui/badge";
import { cn } from "@/lib/utils";

export interface ProductCardData {
	id: string;
	name: string;
	slug: string;
	brand?: string | null;
	price: number;
	compareAtPrice?: number | null;
	currency: string;
	image: string;
	imageAlt?: string;
	hoverImage?: string | null;
	href: string;
	badge?: "Sale" | "New" | "Oferta" | "Nuevo" | null;
	colors?: { name: string; hex: string }[];
	/** Available sizes for filtering (e.g., ["S", "M", "L"]) */
	sizes?: string[];
	/** Category for filtering */
	category?: { id: string; name: string; slug: string } | null;
	/** ISO date string for "newest" sorting */
	createdAt?: string | null;
	/** Whether this product has variants requiring selection (no quick add) */
	hasVariants?: boolean;
	/** Callback for quick add - if provided and no variants, enables quick add */
	onQuickAdd?: (productId: string) => void;
}

interface ProductCardProps {
	product: ProductCardData;
	priority?: boolean;
}

export function ProductCard({ product, priority = false }: ProductCardProps) {
	const canQuickAdd = !product.hasVariants && product.onQuickAdd;

	const handleQuickAdd = (e: React.MouseEvent) => {
		e.preventDefault();
		e.stopPropagation();
		product.onQuickAdd?.(product.id);
	};

	const formatPrice = (amount: number, currency: string) => {
		return new Intl.NumberFormat("es-CL", {
			style: "currency",
			currency: currency,
		}).format(amount);
	};

	return (
		<article className="group">
			<Link href={product.href} className="block">
				{/* Image Container */}
				<div className="relative mb-4 aspect-[3/4] overflow-hidden rounded-xl bg-secondary">
					{/* Primary Image */}
					<Image
						src={product.image}
						alt={product.imageAlt || product.name}
						fill
						sizes="(max-width: 1024px) 50vw, 33vw"
						className={cn(
							"object-cover transition-all duration-500 ease-out md:group-hover:scale-105",
							product.hoverImage && "md:group-hover:opacity-0",
						)}
						priority={priority}
					/>

					{/* Hover Image - desktop only to avoid double-tap on touch */}
					{product.hoverImage && (
						<Image
							src={product.hoverImage}
							alt={`${product.name} - vista alternativa`}
							fill
							sizes="(max-width: 1024px) 50vw, 33vw"
							className="object-cover opacity-0 transition-all duration-500 ease-out md:group-hover:scale-105 md:group-hover:opacity-100"
						/>
					)}

					{/* Badge */}
					{product.badge && (
						<Badge
							variant={product.badge === "Sale" || product.badge === "Oferta" ? "destructive" : "default"}
							className="absolute left-3 top-3"
						>
							{product.badge === "Sale" ? "Oferta" : product.badge === "New" ? "Nuevo" : product.badge}
						</Badge>
					)}

					{/* Agregar rápido Overlay - solo desktop para evitar doble tap en touch */}
					{canQuickAdd && (
						<div className="absolute bottom-0 left-0 right-0 hidden translate-y-2 p-3 opacity-0 transition-all duration-300 md:block md:group-hover:translate-y-0 md:group-hover:opacity-100">
							<Button className="w-full" size="sm" onClick={handleQuickAdd} type="button">
								<Plus className="mr-1.5 h-4 w-4" />
								Agregar
							</Button>
						</div>
					)}
				</div>

				{/* Product Info */}
				<div className="space-y-1.5">
					{product.brand && <p className="text-xs tracking-wide text-muted-foreground">{product.brand}</p>}
					<h3 className="line-clamp-2 font-medium leading-snug underline-offset-2 md:group-hover:underline">
						{product.name}
					</h3>

					{/* Color Swatches */}
					{product.colors && product.colors.length > 1 && (
						<div className="flex items-center gap-1.5 pt-1">
							{product.colors.slice(0, 4).map((color) => (
								<span
									key={color.name}
									className="h-4 w-4 rounded-full border border-border"
									style={{ backgroundColor: color.hex }}
									title={color.name}
								/>
							))}
							{product.colors.length > 4 && (
								<span className="ml-0.5 text-xs text-muted-foreground">+{product.colors.length - 4}</span>
							)}
						</div>
					)}

					{/* Price */}
					<div className="flex items-center gap-2 pt-0.5">
						<span className="font-semibold">{formatPrice(product.price, product.currency)}</span>
						{product.compareAtPrice && (
							<span className="text-sm text-muted-foreground line-through">
								{formatPrice(product.compareAtPrice, product.currency)}
							</span>
						)}
					</div>
				</div>
			</Link>
		</article>
	);
}
